[package]
name = "iata"
version = "0.11.0-alpha.1"
edition = "2021"
authors = [
    "Anton Dutov <anton.dutov@gmail.com>",
    "Mike Lubinets <lubinetsm@yandex.ru>",
    "Martin Mroz <martinmroz@gmail.com>",
    "Innokentii Meleshchenko <innocentuslime.help@gmail.com>",
]
readme = "README.md"
license = "MIT"
description = "Some implementations of IATA resolutions"
repository = "https://github.com/anton-dutov/iata-rs"
categories = ["parser-implementations"]
keywords = ["iata", "bcbp"]

[features]
default = ["with-bcbp"]
with-bcbp = ["dep:paste", "dep:tracing"]
with-serde = ["serde", "jiff/serde"]

[dependencies]
tracing = { version = "0.1", optional = true }
thiserror = "2"
jiff = "0.2"
paste = { version = "1", optional = true }
serde = { version = "1", optional = true, features = ["derive"] }

[dev-dependencies]
rand = "0.9"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
